import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/redux/ReduxProvider/ReduxProvider";
import { Toaster } from "react-hot-toast";
const rajdhani = Rajdhani({ subsets: ["latin"], weight: "600" });

export const metadata: Metadata = {
  title: "Drag Master",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rajdhani.className}>
        <ReduxProvider>{children}</ReduxProvider>
        <Toaster />
      </body>
    </html>
  );
}
